package com.bloodlink.ui;
import com.bloodlink.model.*; import com.bloodlink.service.AppointmentService; import com.bloodlink.util.Theme; import javax.swing.*; import javax.swing.border.EmptyBorder; import javax.swing.table.DefaultTableModel; import java.awt.*; import java.time.*; import java.util.List;
public final class AppointmentPanel extends JPanel {
 private final AppointmentService service; private final DefaultTableModel model=new DefaultTableModel(new Object[]{"ID","Donor","Group","Date","Time","Branch","Status"},0){public boolean isCellEditable(int r,int c){return false;}}; private final JTable table=Theme.styleTable(new JTable(model)); private List<Appointment> current;
 public AppointmentPanel(AppointmentService service){this.service=service;setLayout(new BorderLayout(0,16));setBackground(Theme.BG);setBorder(new EmptyBorder(24,24,24,24));add(header(),BorderLayout.NORTH);JPanel c=Theme.card();c.setLayout(new BorderLayout());c.add(new JScrollPane(table),BorderLayout.CENTER);add(c,BorderLayout.CENTER);refresh();}
 private JPanel header(){JPanel p=new JPanel(new BorderLayout());p.setOpaque(false);JPanel t=new JPanel();t.setOpaque(false);t.setLayout(new BoxLayout(t,BoxLayout.Y_AXIS));t.add(Theme.title("Donation appointments"));t.add(Box.createVerticalStrut(5));t.add(Theme.subtitle("Schedule donor visits and manage branch capacity."));JPanel a=new JPanel(new FlowLayout(FlowLayout.RIGHT,8,0));a.setOpaque(false);JButton cancel=Theme.secondary("Cancel selected");cancel.addActionListener(e->cancel());JButton add=Theme.primary("+ Book appointment");add.addActionListener(e->book());a.add(cancel);a.add(add);p.add(t,BorderLayout.WEST);p.add(a,BorderLayout.EAST);return p;}
 private void refresh(){current=service.all();model.setRowCount(0);for(Appointment a:current)model.addRow(new Object[]{a.getId(),a.getDonorName(),a.getBloodGroup(),a.getDate(),a.getTime(),a.getBranch(),a.getStatus()});}
 private void book(){JTextField donor=new JTextField(),date=new JTextField(LocalDate.now().plusDays(1).toString()),time=new JTextField("10:00"),branch=new JTextField("Pune Central");JComboBox<BloodGroup>g=new JComboBox<>(BloodGroup.values());Object[]f={"Donor name",donor,"Blood group",g,"Date (YYYY-MM-DD)",date,"Time (HH:MM)",time,"Branch",branch};if(JOptionPane.showConfirmDialog(this,f,"Book appointment",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){try{service.book(donor.getText(),(BloodGroup)g.getSelectedItem(),LocalDate.parse(date.getText()),LocalTime.parse(time.getText()),branch.getText());refresh();}catch(Exception ex){JOptionPane.showMessageDialog(this,ex.getMessage(),"Appointment",JOptionPane.ERROR_MESSAGE);}}}
 private void cancel(){int r=table.getSelectedRow();if(r<0){JOptionPane.showMessageDialog(this,"Select an appointment first.");return;}service.cancel(current.get(r));refresh();}
}
