package com.bloodlink.ui;
import com.bloodlink.model.*; import com.bloodlink.service.DonorService; import com.bloodlink.util.Theme; import javax.swing.*; import javax.swing.border.EmptyBorder; import javax.swing.table.DefaultTableModel; import java.awt.*; import java.time.LocalDate; import java.util.List;
public final class DonorPanel extends JPanel {
 private final DonorService service; private final JTextField search=new JTextField(); private final DefaultTableModel model=new DefaultTableModel(new Object[]{"ID","Name","Group","Age","Phone","City","Available","Donations"},0){public boolean isCellEditable(int r,int c){return false;}}; private JTable table=Theme.styleTable(new JTable(model)); private List<Donor> current;
 public DonorPanel(DonorService service){this.service=service;setLayout(new BorderLayout(0,16));setBackground(Theme.BG);setBorder(new EmptyBorder(24,24,24,24));add(top(),BorderLayout.NORTH);add(Theme.card(),BorderLayout.CENTER);JPanel card=(JPanel)getComponent(1);card.setLayout(new BorderLayout());card.add(new JScrollPane(table),BorderLayout.CENTER);refresh("");}
 private JPanel top(){JPanel wrap=new JPanel(new BorderLayout(12,12));wrap.setOpaque(false);JPanel head=new JPanel();head.setOpaque(false);head.setLayout(new BoxLayout(head,BoxLayout.Y_AXIS));head.add(Theme.title("Donor management"));head.add(Box.createVerticalStrut(5));head.add(Theme.subtitle("Maintain verified donor profiles and availability."));wrap.add(head,BorderLayout.NORTH);JPanel actions=new JPanel(new BorderLayout(10,0));actions.setOpaque(false);search.setPreferredSize(new Dimension(330,40));search.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(Theme.BORDER),new EmptyBorder(8,10,8,10)));search.addActionListener(e->refresh(search.getText()));JButton find=Theme.secondary("Search");find.addActionListener(e->refresh(search.getText()));JButton add=Theme.primary("+ Add donor");add.addActionListener(e->addDonor());JButton del=Theme.secondary("Delete selected");del.addActionListener(e->deleteSelected());JPanel right=new JPanel(new FlowLayout(FlowLayout.RIGHT,8,0));right.setOpaque(false);right.add(find);right.add(del);right.add(add);actions.add(search,BorderLayout.WEST);actions.add(right,BorderLayout.EAST);wrap.add(actions,BorderLayout.SOUTH);return wrap;}
 private void refresh(String q){current=q==null||q.isBlank()?service.all():service.search(q);model.setRowCount(0);for(Donor d:current)model.addRow(new Object[]{d.getId(),d.getName(),d.getBloodGroup(),d.getAge(),d.getPhone(),d.getCity(),d.isAvailable()?"Yes":"No",d.getTotalDonations()});}
 private void addDonor(){JTextField name=new JTextField(), email=new JTextField(),age=new JTextField(),phone=new JTextField(),city=new JTextField();JComboBox<BloodGroup> group=new JComboBox<>(BloodGroup.values());JCheckBox available=new JCheckBox("Available to donate",true);Object[] f={"Full name",name,"Email",email,"Blood group",group,"Age",age,"Phone",phone,"City",city,available};if(JOptionPane.showConfirmDialog(this,f,"Add donor",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE)==JOptionPane.OK_OPTION){try{Donor d=new Donor(0,name.getText().trim(),email.getText().trim(),(BloodGroup)group.getSelectedItem(),Integer.parseInt(age.getText().trim()),phone.getText().trim(),city.getText().trim(),LocalDate.now().minusMonths(4),available.isSelected(),0);service.save(d);refresh(search.getText());}catch(Exception ex){JOptionPane.showMessageDialog(this,ex.getMessage(),"Unable to save donor",JOptionPane.ERROR_MESSAGE);}}}
 private void deleteSelected(){int row=table.getSelectedRow();if(row<0){JOptionPane.showMessageDialog(this,"Select a donor first.");return;}Donor d=current.get(row);if(JOptionPane.showConfirmDialog(this,"Delete "+d.getName()+"?","Confirm",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){service.delete(d.getId());refresh(search.getText());}}
}
