package com.bloodlink.ui;
import com.bloodlink.model.*; import com.bloodlink.service.RequestService; import com.bloodlink.util.Theme; import javax.swing.*; import javax.swing.border.EmptyBorder; import javax.swing.table.DefaultTableModel; import java.awt.*; import java.time.format.DateTimeFormatter; import java.util.List;
public final class RequestPanel extends JPanel {
 private final RequestService service; private final DefaultTableModel model=new DefaultTableModel(new Object[]{"ID","Patient","Group","Units","Hospital","Priority","Status","Created"},0){public boolean isCellEditable(int r,int c){return false;}}; private final JTable table=Theme.styleTable(new JTable(model)); private List<BloodRequest> current;
 public RequestPanel(RequestService service){this.service=service;setLayout(new BorderLayout(0,16));setBackground(Theme.BG);setBorder(new EmptyBorder(24,24,24,24));add(header(),BorderLayout.NORTH);JPanel c=Theme.card();c.setLayout(new BorderLayout());c.add(new JScrollPane(table),BorderLayout.CENTER);add(c,BorderLayout.CENTER);refresh();}
 private JPanel header(){JPanel p=new JPanel(new BorderLayout());p.setOpaque(false);JPanel t=new JPanel();t.setOpaque(false);t.setLayout(new BoxLayout(t,BoxLayout.Y_AXIS));t.add(Theme.title("Blood requests"));t.add(Box.createVerticalStrut(5));t.add(Theme.subtitle("Emergency-first request workflow with stock checks."));JPanel a=new JPanel(new FlowLayout(FlowLayout.RIGHT,8,0));a.setOpaque(false);JButton add=Theme.primary("+ New request");add.addActionListener(e->create());JButton approve=Theme.secondary("Approve");approve.addActionListener(e->act("approve"));JButton complete=Theme.secondary("Complete");complete.addActionListener(e->act("complete"));JButton reject=Theme.secondary("Reject");reject.addActionListener(e->act("reject"));a.add(reject);a.add(approve);a.add(complete);a.add(add);p.add(t,BorderLayout.WEST);p.add(a,BorderLayout.EAST);return p;}
 private void refresh(){current=service.all();model.setRowCount(0);DateTimeFormatter f=DateTimeFormatter.ofPattern("dd MMM, HH:mm");for(BloodRequest r:current)model.addRow(new Object[]{r.getId(),r.getPatientName(),r.getBloodGroup(),r.getUnits(),r.getHospital(),r.getPriority(),r.getStatus(),r.getCreatedAt().format(f)});}
 private BloodRequest selected(){int row=table.getSelectedRow();return row<0?null:current.get(row);}
 private void act(String action){BloodRequest r=selected();if(r==null){JOptionPane.showMessageDialog(this,"Select a request first.");return;}try{switch(action){case"approve"->service.approve(r);case"complete"->service.complete(r);case"reject"->service.reject(r);}refresh();}catch(Exception ex){JOptionPane.showMessageDialog(this,ex.getMessage(),"Request workflow",JOptionPane.ERROR_MESSAGE);}}
 private void create(){JTextField patient=new JTextField(),hospital=new JTextField(),doctor=new JTextField();JComboBox<BloodGroup>group=new JComboBox<>(BloodGroup.values());JSpinner units=new JSpinner(new SpinnerNumberModel(1,1,10,1));JComboBox<Priority>priority=new JComboBox<>(Priority.values());Object[]f={"Patient name",patient,"Blood group",group,"Units",units,"Hospital",hospital,"Doctor",doctor,"Priority",priority};if(JOptionPane.showConfirmDialog(this,f,"Create blood request",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){try{service.create(patient.getText(),(BloodGroup)group.getSelectedItem(),(Integer)units.getValue(),hospital.getText(),doctor.getText(),(Priority)priority.getSelectedItem());refresh();}catch(Exception ex){JOptionPane.showMessageDialog(this,ex.getMessage(),"Request",JOptionPane.ERROR_MESSAGE);}}}
}
